version: '3.1'

services:

  zookeeper:
    container_name: zookeeper
    image: confluent/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    build: ./kafka
    links:
     - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "content-watched:10:1"

  ksql-anonymization:
    container_name: ksql-anonymization
    build: ./ksql-anonymization
    ports:
      - "8088:8088"
      - "9001:9000"
    depends_on:
      - kafka
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:9093
      KSQL_KSQL_SERVICE_ID: ksql-anonymization
      KSQL_LISTENERS: http://0.0.0.0:8088
    restart: always


# Monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - ./prometheus:/etc/prometheus
    links:
      - kafka

  grafana:
    container_name: grafana
    image: grafana/grafana:5.2.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: always

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
