global:
  scrape_interval: 5s

scrape_configs:

- job_name: kafka
  static_configs:
  - targets: ['kafka:9000']

- job_name: ksql
  static_configs:
  - targets: ['ksql-anonymization:9000']

- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'cadvisor'
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: 'node-exporter'
  static_configs:
  - targets: ['node-exporter:9100']